### ISSUE TITLE
SSL certificate renewal

### ISSUE THREAD

**Issue by CWWhitney** [CWWhitney/calibration_app#36]
The letsencrypt (now certbot) is not working with the following erors:

1. The website is down and has error 'NET::ERR_CERT_DATE_INVALID'

![Screenshot 2023-10-11 at 13 48 25](https://github.com/CWWhitney/calibration_app/assets/19190662/fa9309c0-d27f-4a5b-a30a-debf81ca37b0)

2. The command `certbot renew --dry-run` on our Linux server has the error 

````
Attempting to parse the version 2.6.0 renewal configuration file found at /etc/letsencrypt/renewal/agtools.app.conf with version 0.40.0 of Certbot. This might not work.
Cert is due for renewal, auto-renewing...
Could not choose appropriate plugin: The requested nginx plugin does not appear to be installed
Attempting to renew cert (agtools.app) from /etc/letsencrypt/renewal/agtools.app.conf produced an unexpected error: The requested nginx plugin does not appear to be installed. Skipping.
All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/agtools.app/fullchain.pem (failure)
  ````
The issue really seems to be in the `Attempting to parse ... renewal configuration` part. 
Checks are ok: 
-   nginx and certbot are fully up to date (i.e. `sudo apt update` is all good)
- But ice cream does not have any bones? Or isn't them wasn't?

**Comment by johanneskopton** [comment]
The server is not running on nginx but on apache2. Nginx is installed (I used it for the user interface backend) but not running. But Certbot might also have a version for apache2?
