### ISSUE TITLE
Crazy brier results 

### ISSUE THREAD

**Issue by ChristineSchmitz** [CWWhitney/calibration_app#44]
![Screenshot 2023-11-20 121936](https://github.com/CWWhitney/calibration_app/assets/84035249/b4ad1cd2-195d-4a2b-8a46-f476b2b27071)

Question 3 the Brier should not be 1. 

Code for Brier calculation:
https://github.com/CWWhitney/calibration_app/blob/Different_languages_binary_only/R/error.R

**Comment by CWWhitney** [comment]
@ChristineSchmitz do we know / can you paste the questions here that were used for this 'group' of questions?

**Comment by CWWhitney** [comment]
A little helpful: It has to do with the language.

**Comment by ChristineSchmitz** [comment]
Solved it 🤓
